### ISSUE TITLE
Upstream to ansible/contrib

### ISSUE THREAD

**Issue by siwyd** [hg8496/ansible-hcloud-inventory#9]
Do you have plans to upstream this to the Ansible repo in the contrib directory? It would be nice if people could simply find it over there. The inventory works nicely, seems worthwhile to get it included upstream.

**Comment by hg8496** [comment]
No plans so far. I will give it a try.

**Comment by MaxPeal** [comment]
any news on this?

**Comment by siwyd** [comment]
@MaxPeal The new inventory plugin system has a Hetzner Cloud plugin: https://docs.ansible.com/ansible/latest/plugins/inventory/hcloud.html. I've since switched to that one. I'm gonna close this ticket.

**Comment by MaxPeal** [comment]
@siwyd thanks for the info!
